version: "2.4"

services:

  portainer:
    image: portainer/portainer-ce
    restart: unless-stopped
    environment:
      - TZ=${GLOBAL_TZ}
    labels:
      traefik.frontend.priority: 1
      traefik.enable: true
      traefik.http.routers.portainer.rule: "HostRegexp(`portainer.admin.rosterboss.{suffix:[a-z]+}`)"
      traefik.http.routers.portainer.entrypoints: web
      traefik.http.routers.portainer_https.rule: "HostRegexp(`portainer.admin.rosterboss.{suffix:[a-z]+}`)"
      traefik.http.routers.portainer_https.tls: true
      traefik.http.routers.portainer_https.entrypoints: websecure
      traefik.http.services.portainer.loadbalancer.server.port: 9000
      traefik.http.services.portainer.loadbalancer.passHostHeader: true
      #traefik.http.routers.portainer.middlewares: adminservice-auth
    volumes:
      - portainer-data:/data
    networks:
      - internal
      - monitoring
    profiles:
      - portainer

  portainer-agent:
    image: portainer/agent
    restart: unless-stopped
    environment:
      TZ: "${GLOBAL_TZ}"
      AGENT_CLUSTER_ADDR: tasks.portainer_agent
      CAP_HOST_MANAGEMENT: '1'
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /var/lib/docker/volumes:/var/lib/docker/volumes
      - /:/host
    networks:
      - internal
      - monitoring
    profiles:
      - portainer

networks:
  internal:
  monitoring:

volumes:
  portainer-data:
